// Code generated by goderive DO NOT EDIT.

package main

import (
	"sort"
)

// deriveSort sorts the slice inplace and also returns it.
func deriveSort(list []int) []int {
	sort.Ints(list)
	return list
}

// deriveKeys returns the keys of the input map as a slice.
func deriveKeys(m map[int]int) []int {
	keys := make([]int, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	return keys
}
